a) 20 - esperado
b) 29.0 - esperado
c) p - esperado
d) e - esperado
e) P - esperado 
f) e - esperado 
g) t - esperado 
h) 31 - esperado
i) 45 - esperado
j) 27 - esperado 
k) 31 - esperado
l) 45 - esperado
m) 27 - esperado
